export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_FAIL = "EDIT_USER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_ATTENDANCES = "GET_ATTENDANCES";
export const GET_ATTENDANCE = "GET_ATTENDANCE";
export const ADD_ATTENDANCE = "ADD_ATTENDANCE";
export const EDIT_ATTENDANCE = "EDIT_ATTENDANCE";
export const DELETE_ATTENDANCE = "DELETE_ATTENDANCE";
export const ATTENDANCES_LOADING = "ATTENDANCES_LOADING";
export const ATTENDANCE_LOADING = "ATTENDANCE_LOADING";
export const TOGGLE_EDIT_ATT_MODAL = "TOGGLE_EDIT_ATT_MODAL";
export const TOGGLE_VIEW_ATT_MODAL = "TOGGLE_VIEW_ATT_MODAL";

export const OPEN_ACTIONS_BUTTON = "OPEN_ACTIONS_BUTTON";
export const CLOSE_ACTIONS_BUTTON = "CLOSE_ACTIONS_BUTTON";

export const ACTIONS_BUTTON_EDIT = "ACTIONS_BUTTON_EDIT";
export const ACTIONS_BUTTON_VIEW = "ACTIONS_BUTTON_VIEW";
export const ACTIONS_BUTTON_DELETE = "ACTIONS_BUTTON_DELETE";

export const RESET_REGISTER = "RESET_REGISTER";
export const RESET_EDIT_USER = "RESET_EDIT_USER";
export const RESET_DELETE_USER = "RESET_DELETE_USER";

export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const EDIT_USER = "EDIT_USER";
export const USERS_LOADING = "USERS_LOADING";
export const TOGGLE_EDIT_USER_MODAL = "TOGGLE_EDIT_USER_MODAL";
export const TOGGLE_VIEW_USER_MODAL = "TOGGLE_VIEW_USER_MODAL";

// CC_API 

export const GET_USER_ROLES = "GET_USER_ROLES";
export const CC_API_AUTH_SUCCESS = "LOGIN_SUCCESS";
export const CC_API_AUTH_FAIL = "LOGIN_FAIL";

export const GET_WORKERS = "GET_WORKERS";
export const GET_WORKER = "GET_WORKER";
export const WORKERS_LOADING = "WORKERS_LOADING";
export const WORKER_LOADING = "WORKER_LOADING";
export const ADD_WORKER = "ADD_WORKER";
export const EDIT_WORKER = "EDIT_WORKER";
export const DELETE_WORKER = "DELETE_WORKER";
export const RESTORE_WORKER = "RESTORE_WORKER";
export const TOOGLE_WORKER_MODAL = "TOOGLE_WORKER_MODAL";
export const TOOGLE_EDIT_WORKER_MODAL = "TOOGLE_EDIT_WORKER_MODAL";
export const TOOGLE_VIEW_WORKER_MODAL = "TOOGLE_VIEW_WORKER_MODAL";

export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const DELETE_POST = "DELETE_POST";

export const POSTS_LOADING = "POSTS_LOADING";
export const POST_LOADING = "POST_LOADING";

export const ADD_ATT_SUCCESS = "ADD_ATT_SUCCESS";
export const ADD_ATT_FAIL = "ADD_ATT_FAIL";
export const DELETE_ATT_SUCCESS = "DELETE_ATT_SUCCESS";
export const DELETE_ATT_FAIL = "DELETE_ATT_FAIL";
export const EDIT_ATT_SUCCESS = "EDIT_ATT_SUCCESS";
export const EDIT_ATT_FAIL = "EDIT_ATT_FAIL";

export const ADD_WORKER_SUCCESS = "ADD_WORKER_SUCCESS";
export const ADD_WORKER_FAIL = "ADD_WORKER_FAIL";
export const EDIT_WORKER_SUCCESS = "EDIT_WORKER_SUCCESS";
export const EDIT_WORKER_FAIL = "EDIT_WORKER_FAIL";
export const RESTORE_WORKER_SUCCESS = "RESTORE_WORKER_SUCCESS";
export const RESTORE_WORKER_FAIL = "RESTORE_WORKER_FAIL";
export const DELETE_WORKER_SUCCESS = "DELETE_WORKER_SUCCESS";
export const DELETE_WORKER_FAIL = "DELETE_WORKER_FAIL";

export const RESET_ADD_ATT = "RESET_ADD_ATT";
export const RESET_EDIT_ATT = "RESET_EDIT_ATT";
export const RESET_DELETE_ATT = "RESET_DELETE_ATT";

export const RESET_ADD_WORKER = "RESET_ADD_WORKER";
export const RESET_EDIT_WORKER = "RESET_EDIT_WORKER";
export const RESET_DELETE_WORKER = "RESET_DELETE_WORKER";
export const RESET_RESTORE_WORKER = "RESET_RESTORE_WORKER";

export const SHOW_ADD_ATT_SUCCESS_TOAST = "SHOW_ADD_ATT_SUCCESS_TOAST";
export const SHOW_EDIT_ATT_SUCCESS_TOAST = "SHOW_EDIT_ATT_SUCCESS_TOAST";
export const SHOW_DELETE_ATT_SUCCESS_TOAST = "SHOW_DELETE_ATT_SUCCESS_TOAST";
export const SHOW_ADD_ATT_FAIL_TOAST = "SHOW_ADD_ATT_FAIL_TOAST";
export const SHOW_EDIT_ATT_FAIL_TOAST = "SHOW_EDIT_ATT_FAIL_TOAST";
export const SHOW_DELETE_ATT_FAIL_TOAST = "SHOW_DELETE_ATT_FAIL_TOAST";

export const SHOW_ADD_USER_SUCCESS_TOAST = "SHOW_ADD_USER_SUCCESS_TOAST";
export const SHOW_ADD_USER_FAIL_TOAST = "SHOW_ADD_USER_FAIL_TOAST";
export const SHOW_DELETE_USER_SUCCESS_TOAST = "SHOW_DELETE_USER_SUCCESS_TOAST";
export const SHOW_DELETE_USER_FAIL_TOAST = "SHOW_DELETE_USER_FAIL_TOAST";
export const SHOW_EDIT_USER_SUCCESS_TOAST = "SHOW_EDIT_USER_SUCCESS_TOAST";
export const SHOW_EDIT_USER_FAIL_TOAST = "SHOW_EDIT_USER_FAIL_TOAST";
export const SHOW_EDIT_WORKER_SUCCESS_TOAST = "SHOW_EDIT_WORKER_SUCCESS_TOAST";
export const SHOW_EDIT_WORKER_FAIL_TOAST = "SHOW_EDIT_WORKER_FAIL_TOAST";
export const SHOW_FAIL_TOAST = "SHOW_FAIL_TOAST";
export const SHOW_SUCCESS_TOAST = "SHOW_SUCCESS_TOAST";
export const SHOW_RESTORE_WORKER_SUCCESS_TOAST = "SHOW_RESTORE_WORKER_SUCCESS_TOAST"
export const SHOW_RESTORE_WORKER_FAIL_TOAST = "SHOW_RESTORE_WORKER_FAIL_TOAST"

export const GET_MINISTRY_ARMS = "GET_MINISTRY_ARMS";
export const GET_MINISTRY_ARM = "GET_MINISTRY_ARM";
export const ADD_MINISTRY_ARM = "ADD_MINISTRY_ARM";
export const EDIT_MINISTRY_ARM = "EDIT_MINISTRY_ARM";
export const DELETE_MINISTRY_ARM = "DELETE_MINISTRY_ARM";
export const MINISTRY_ARMS_LOADING = "MINISTRY_ARMS_LOADING";
export const MINISTRY_ARM_LOADING = "MINISTRY_ARM_LOADING";
export const TOGGLE_EDIT_MA_MODAL = "TOGGLE_EDIT_MA_MODAL";
export const TOGGLE_VIEW_MA_MODAL = "TOGGLE_VIEW_MA_MODAL";

export const ADD_MA_SUCCESS = "ADD_MA_SUCCESS";
export const ADD_MA_FAIL = "ADD_MA_FAIL";
export const DELETE_MA_SUCCESS = "DELETE_MA_SUCCESS";
export const DELETE_MA_FAIL = "DELETE_MA_FAIL";
export const EDIT_MA_SUCCESS = "EDIT_MA_SUCCESS";
export const EDIT_MA_FAIL = "EDIT_MA_FAIL";

export const RESET_ADD_MA = "RESET_ADD_MA";
export const RESET_EDIT_MA = "RESET_EDIT_MA";
export const RESET_DELETE_MA = "RESET_DELETE_MA";

export const SHOW_ADD_MA_SUCCESS_TOAST = "SHOW_ADD_MA_SUCCESS_TOAST";
export const SHOW_EDIT_MA_SUCCESS_TOAST = "SHOW_EDIT_MA_SUCCESS_TOAST";
export const SHOW_DELETE_MA_SUCCESS_TOAST = "SHOW_DELETE_MA_SUCCESS_TOAST";
export const SHOW_ADD_MA_FAIL_TOAST = "SHOW_ADD_MA_FAIL_TOAST";
export const SHOW_EDIT_MA_FAIL_TOAST = "SHOW_EDIT_MA_FAIL_TOAST";
export const SHOW_DELETE_MA_FAIL_TOAST = "SHOW_DELETE_MA_FAIL_TOAST";
export const SHOW_RESTORE_MA_FAIL_TOAST = "SHOW_RESTORE_MA_FAIL_TOAST";
export const SHOW_RESTORE_MA_SUCCESS_TOAST = "SHOW_RESTORE_MA_SUCCESS_TOAST";

export const GET_DIRECTORATES = "GET_DIRECTORATES";
export const GET_DIRECTORATE = "GET_DIRECTORATE";
export const ADD_DIRECTORATE = "ADD_DIRECTORATE";
export const EDIT_DIRECTORATE = "EDIT_DIRECTORATE";
export const DELETE_DIRECTORATE = "DELETE_DIRECTORATE";
export const DIRECTORATES_LOADING = "DIRECTORATES_LOADING";
export const DIRECTORATE_LOADING = "DIRECTORATE_LOADING";
export const TOGGLE_EDIT_DIRECTORATE_MODAL = "TOGGLE_EDIT_DIRECTORATE_MODAL";
export const TOGGLE_VIEW_DIRECTORATE_MODAL = "TOGGLE_VIEW_DIRECTORATE_MODAL";

export const ADD_DIRECTORATE_SUCCESS = "ADD_DIRECTORATE_SUCCESS";
export const ADD_DIRECTORATE_FAIL = "ADD_DIRECTORATE_FAIL";
export const DELETE_DIRECTORATE_SUCCESS = "DELETE_DIRECTORATE_SUCCESS";
export const DELETE_DIRECTORATE_FAIL = "DELETE_DIRECTORATE_FAIL";
export const EDIT_DIRECTORATE_SUCCESS = "EDIT_DIRECTORATE_SUCCESS";
export const EDIT_DIRECTORATE_FAIL = "EDIT_DIRECTORATE_FAIL";

export const RESET_ADD_DIRECTORATE = "RESET_ADD_DIRECTORATE";
export const RESET_EDIT_DIRECTORATE = "RESET_EDIT_DIRECTORATE";
export const RESET_DELETE_DIRECTORATE = "RESET_DELETE_DIRECTORATE";

export const SHOW_ADD_DIRECTORATE_SUCCESS_TOAST = "SHOW_ADD_DIRECTORATE_SUCCESS_TOAST";
export const SHOW_EDIT_DIRECTORATE_SUCCESS_TOAST = "SHOW_EDIT_DIRECTORATE_SUCCESS_TOAST";
export const SHOW_DELETE_DIRECTORATE_SUCCESS_TOAST = "SHOW_DELETE_DIRECTORATE_SUCCESS_TOAST";
export const SHOW_ADD_DIRECTORATE_FAIL_TOAST = "SHOW_ADD_DIRECTORATE_FAIL_TOAST";
export const SHOW_EDIT_DIRECTORATE_FAIL_TOAST = "SHOW_EDIT_DIRECTORATE_FAIL_TOAST";
export const SHOW_DELETE_DIRECTORATE_FAIL_TOAST = "SHOW_DELETE_DIRECTORATE_FAIL_TOAST";

export const SHOW_ADD_WORKER_FAIL_TOAST = "SHOW_ADD_WORKER_FAIL_TOAST";
export const SHOW_ADD_WORKER_SUCCESS_TOAST = "SHOW_ADD_WORKER_SUCCESS_TOAST";
export const SHOW_DELETE_WORKER_FAIL_TOAST = "SHOW_DELETE_WORKER_FAIL_TOAST";
export const SHOW_DELETE_WORKER_SUCCESS_TOAST = "SHOW_DELETE_WORKER_SUCCESS_TOAST";
//export const = "";